/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import Vo.Archivos;
import negocio.Controlador;
import com.sun.corba.se.impl.orbutil.ORBConstants;
import com.sun.org.apache.xml.internal.security.encryption.AgreementMethod;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

//import negocio.Controlador;
/**
 *
 * @author steven
 */
public class frameView1 extends javax.swing.JFrame{
private int Control;
    /**
     * Creates new form frameView1
     */
    public frameView1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contador de Lineas psp1");

        jLabel2.setText("Presione el boton \"Abrir\" para escoger el archivo ");

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Numero de lineas", "Numero de metodos ", "Numero de clases", "Numero de comentarios"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane3.setViewportView(TextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser ventana= new JFileChooser();
        ventana.showOpenDialog(this); //e.e
        int lineas=0;
        System.out.println("OPTION : " +ventana.APPROVE_OPTION);
        if(ventana.APPROVE_OPTION==0)
        {
            
            Control++;
            try {
                AgregarATabla(ventana.getSelectedFile(),jTable1,Control);
                //Controlador().AgregarATabla(ventana.getSelectedFile(),jTable1);
            } catch (IOException ex) {
                Logger.getLogger(frameView1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        System.out.println("Total de lineas en el archivo : "+lineas);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameView1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    ////////////
    public void AgregarATabla (File f, JTable tabla,int control) throws IOException, NullPointerException
    {
     
     //   Object columnNames []= {   "Nombre", "Numero de lineas", "Numero de metodos ", "Numero de clases", "Numero de comentarios"};
        
          /*jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Numero de lineas", "Numero de metodos ", "Numero de clases", "Numero de comentarios"
            }
        */
        
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        
        /*Archivos ar=new Archivos();
        ar.setId(control+"");
        ar.setName(f.getName());        
        ar.setN_lineas(contarlineas(f));
        ar.setN_metodos(countMeto(f));
        ar.setN_clases(countClass(f));
        ar.setN_comentarios(countComent(f));*/
            BufferedReader lector;            
                lector = new BufferedReader(new FileReader(f));
             //Scanner lector = new Scanner(f);
                
                int id;
                String name;
                int line=0;
                int methods=0;
                int classs=0;
                int  coments=0;
                String value="";
                int contador=0;
                while(lector.ready() || contador ==200)
                {
                    
                    value=value+lector.readLine()+"\n";
                    
                    contador++;
                    if (contador==199)
                    {
                           System.out.println("Huston We have a problem !! :c");
                    }
                    /**/
                    try {
                        line++;
                        /*
                    if(lector.readLine().contains("public")||lector.readLine().contains("private"))
                        methods++;
                    if(lector.readLine().contains(" class "))
                        classs++;
                    if(lector.readLine().contains("//"))
                        coments++;
                    */
                    } catch ( NullPointerException e) {
                    }
                    

                    
                    
                }

                methods=_contar(value, "public")+_contar(value, "private");
                classs=_contar(value, " class ");
                coments=_contar(value, "//");
                
                TextArea1.setText(value);
                System.out.println("Lines: "+line+"\nMethods: "+ methods+"\nClass: "+classs+"\ncoments : "+coments);
                    Archivos ar = new Archivos(control+"", f.getName(), line+"",methods+"", classs+"",coments+"");
        model.addRow(new Object[]{ar.getId(),ar.getName(),ar.getN_lineas(),ar.getN_metodos(),ar.getN_clases(),ar.getN_comentarios()});
    }

    public int _contar(String value,String value2)
    {
        int contador=0;
        while (value.indexOf(value2) > -1 ) {
            value = value.substring(value.indexOf(value2)+value2.length(),value.length());                 
            contador++; 
        }
        return contador;
    }
    ///////////////////
    
}
